### ISSUE TITLE
Passing note from Sagar

### ISSUE THREAD

**Issue by ionicc** [HAC-2020/X-A-4#1]
Hey guys, Hope you're having a great day!

I noticed that you pushed the entire front-end code in one commit.

https://github.com/HAC-2020/X-A-4/commit/2c7a271ff1c0e057e10a26da40971ae9fe7511a4

This was specifically mentioned not to be done. Please explain the reason in this thread.

**Comment by abhay8463** [comment]
Hello, yaa we pushed all the code at once since we were not able to push it
per component-wise.
We were trying from tomorrow night to push at the time we completed each
component of our dashboard
But it was giving some merge issues
So due to time constraint, and we completed all the components at that
particular time we had to push the whole code at once
Sorry for the violation.But we were unable to do it since we had to push
Hope you understand

**Comment by ionicc** [comment]
@abhay8463 Completely understood, No problem! Can you now (Going forward) do the commits feature-wise and frequently?

**Comment by abhay8463** [comment]
Yes we will surely try to do it that way.
